# Generated by Django 5.1.6 on 2025-02-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
